export default function BlogPage() {
  return (
    <div class="blog-post">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="titlepage text_align_center">
              <h1>Solar Heat System </h1>
            </div>
          </div>
        </div>
        <section class="blog-section">
          <p>
          Solar heating systems can be divided into two groups, passive solar and active solar heating. In essence, these systems harvest thermal energy from the sun and utilize the collected heat for space heating purposes or to heat domestic water. Passive solar systems rely on the structure of the building to collect heat. This could be in the form of a tilt or a roof orientation that allows for higher solar irradiance. On the contrary, active solar heating systems rely on heat pumps that transfer the collected heat from the solar collectors to the building. In contrast to photovoltaic panels that generate electricity, thermal solar panels are used to capture energy from the sun and utilize it to provide the abovementioned commodities.Normally these systems are not designed for stand-alone systems due to the intermittency of the energy source and the lack of viable storage options. However, these systems can be complimentary to other existing heating systems powered by natural gas or other sources.
          </p>
        </section>

        <img
          src="/solar-heat1.webp"
          alt="solar energy"
          class="blog-post__image"
        />
        <section class="blog-section">
          <p>
          Solar heaters are considered an inexpensive way to exploit the heat resulting from sunlight and convert it to benefit by heating the water inside the solar heater. By shedding the sun is heat on solar heaters, it can heat water with ease. Solar heaters can be used for domestic benefit for individuals at home and benefit. Personally, it can also be used commercially as a profitable project.
          </p>
          
        </section> 

        {/* <video src="/video.mp4"></video> */}

        {/* <iframe width="560" height="315" src="https://www.youtube.com/embed/BlyIHrIJoT0?si=JufYMp186iuydrK0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> */}

        <section class="blog-section">
          <h2>The first type</h2>
          <p>
          It is a flat plate solar heater that contains a sheet of glass that protects it from the outside. It works to absorb the heat resulting from the sun's rays. Inside the solar heater there are tubes for water to pass through it, as it works to heat the water that passes inside the tube in the heater. It works with very high quality. The solar heater is covered from the outside with a copper material that is resistant to rust and corrosion. Natural flow heaters are made of stainless steel, which can heat water through the heat generated by the sun’s rays, and the capacity of the heater changes from one heater to another.
          </p>
        </section>

        <img
          src="/solar-heat2.png"
          alt="solar energy"
          class="blog-post__image"
        />
        <section class="blog-section">
          <h2>The second type</h2>
          <p>
          The evacuated tube technology consists of metal tubes surrounded by glass, and air is evacuated between the glass and the metal tube (see the second picture). The sun also heats the pipes and then the water, and with the difference in density of the hot and cold water, the cold water descends into the pipes and the hot water rises to collect in the tank. The benefit of vacuuming is to reduce heat transfer from the metal pipe to the atmosphere.
          </p>
        </section>
        <img
          src="/solar-heat3.jpg"
          alt="solar energy"
          class="blog-post__image"
        />
      </div>
    </div>
  );
}
